version: '3'
services:
  gulp:
    container_name: sphinxgulp
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports: 
    - 3000:3000
    volumes:
      - ./app/:/usr/src/app/work
    tty: true